---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
  - name: app
    run_list:
      - recipe[pathfinder-mono::db]
      - recipe[pathfinder-mono::app]
      - recipe[pathfinder-mono::scheduler]
    driver_config:
      customize:
        memory: 1024
      network:
        - ["private_network", { ip: "192.168.33.10" }]
    verifier:
      inspec_tests:
        - test/integration/db
        - test/integration/app
        - test/integration/scheduler
    attributes:
      app_name: "pathfinder-mono"
      postgresql:
        locale: "en_US.UTF-8"
        replication: true
        db_replication_addr: "192.168.33.11"
        db_replication_username: "repluser"
        db_replication_password: "password1234"
  - name: replication
    run_list:
      - recipe[pathfinder-mono::db_replication]
    driver_config:
      customize:
        memory: 1024
      network:
        - ["private_network", { ip: "192.168.33.11" }]
    verifier:
      inspec_tests:
        - test/integration/app
        - test/unit/spec
    attributes:
      app_name: "pathfinder-mono"
      postgresql:
        db_master_addr: "192.168.33.10"
        db_replication_username: "repluser"
        db_replication_password: "password1234"
